spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    username: sa
    password: 1006
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-date-keys-as-timestamps: false
    time-zone: America/Sao_Paulo